#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "ERROR: El mensaje de su commit no respeta las reglas de 'Conventional Commits'." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "ERROR: El mensaje de su commit es mu largo." >&2
    exit 1
fi